### ISSUE TITLE
What is lifeInEmoji about?

### ISSUE THREAD

**Issue by Kovah** [huijing/personal-website#2]
Hi, just rad your article about overlapping elements and noticed that there was an emoji in the URL. Looked into the source to find out more about it and found https://github.com/huijing/personal-website/blob/main/assets/js/custom.js.
Can you tell more about what lifeInEmoji is and why it only applies to macOS? I am really curious. 😊

**Comment by huijing** [comment]
Oh hello @Kovah! It's a totally frivolous thing where I add a random emoji (from that array of emojis) into the URL of any page on my site. Something like this:

 
<img width="309" alt="Screenshot 2022-09-25 at 10 04 04 PM" src="https://user-images.githubusercontent.com/1461498/192147746-1d9607d6-aa49-4763-8434-dfce0ba4debc.png">
<img width="601" alt="Screenshot 2022-09-25 at 10 04 11 PM" src="https://user-images.githubusercontent.com/1461498/192147751-d93f42b2-57b8-4188-a578-26e6382e1abf.png">
<img width="363" alt="Screenshot 2022-09-25 at 10 04 17 PM" src="https://user-images.githubusercontent.com/1461498/192147754-70063ad4-2507-48fa-a5d3-af8de0c556e7.png">

I put the code in there like more than 6 years ago? (https://github.com/huijing/huijing.github.io/commit/7dc12d8fc91499ac9850d7f3425c0db66d5c4e3e#diff-2ed105cd5226ee70e3a5a8fc8fa88cc6a7e7e22e649966217c3529f61ecbc994) so I really can't remember where I got the idea from anymore.

**Comment by Kovah** [comment]
Haha nice! Neat little feature.
